# makefile for assinment 4 for cs3790
# program by Colby Garland id# 5034957
# memory management

prog: main.o
	g++ main.o -o prog

readWrite.o: readWrite.cpp
	g++ -c main.cpp

clean:
	rm -rf *.o prog
